# Лабораторна робота №1

In [2]:
import numpy as np

# Тема роботи: Бінарні відношення

# Мета роботи: вивчення властивостей бінарних відношень, операцій над відношеннями, набуття навичок прийняття рішень на основі заданих відношень.

## Задача:
Перевірити, чи буде дане відношення рефлексивним, антирефлексивним,
симетричним, антисиметричним, асиметричним, транзитивним. Відшукати
для нього найбільший, найменший , максимальний та мінімальний елементи,
якщо такі існують, і побудувати обернене й додаткове відношення.

Варіант: 9

In [3]:
R = np.array(
    [
        [1, 1, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 1, 1, 1],
        [0, 1, 0, 0, 0]
    ]
)

In [4]:
ref = []
def reflexion(R):
    for i in range(len(R)):
        ref.append(R[i][i])
    result_reflexion = ref[1:] == ref[:-1] and ref[1] == 1
    result_anti_reflexion = ref[1:] == ref[:-1] and ref[1] == 0
    return f" Відношення є рефлексивним: {result_reflexion}, відношення є антирефлексивним: {result_anti_reflexion}"

In [5]:
reflexion(R)

' Відношення є рефлексивним: False, відношення є антирефлексивним: False'

In [6]:
def sym(R):
    sym, antysym, asym = True, True, True

    for i in range(len(R)):
        for j in range(len(R[0])):
            if R[i][j] != R[j][i]:
                sym = False
            if i != j and R[i][j] == 1 == R[j][i]:
                antysym = False
            if R[i][j] ==  R[j][i] == 1:
                asym = False
    return f" Відношення є симетричним : {sym}, відношення є антисиметричним: {antysym}, відношення є асиметричним: {asym}"

In [7]:
sym(R)

' Відношення є симетричним : False, відношення є антисиметричним: False, відношення є асиметричним: False'

In [8]:
def transitive(R):
    r_2 = R@R
    result = True
    for i in range(len(R)):
        for j in range(len(R[0])):
            if r_2[i][j] > R[i][j]:
                result = False
    return f" Відношення є транзитивним : {result}"

In [9]:
transitive(R)

' Відношення є транзитивним : False'

In [10]:
def min_max(R):
    R_S = ((R - np.transpose(R))>0)*1
    print(R_S)

    max, min = [], []

    for i in range(R.shape[0]):
        if (R_S[i]==0).all():
            min.append(i+1)

    for i in range(R.shape[0]):
        if (R_S[..., i]==0).all():
            max.append(i+1)

    return min, max

In [11]:
min_max(R)

[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [0 0 1 0 1]
 [0 1 0 0 0]]


([1], [1])

In [12]:
def larg_tin(R):
    larg = "-"
    tiny = "-"

    for i in range(R.shape[0]):
        if (R[i]==1).all():
            larg = i+1

    for i in range(R.shape[0]):
        if (R[..., i]==1).all():
            tiny = i+1

    return f'Найбільший елемент: {larg}, найменший елемент: {tiny}'

In [14]:
larg_tin(R)

'Найбільший елемент: -, найменший елемент: -'

### обернене й додаткове відношення

In [15]:
def reverse(R):
    result = [[0] * len(R) for _ in range(len(R))]

    for i in range(len(R)):
        for j in range(len(R[0])):
            result[j][i] = R[i][j]

    return result

In [16]:
def print_matrix(R):
    for i in R:
        print(" ".join(str(x) for x in i))

In [17]:
print_matrix(reverse(R))

1 1 0 1 0
1 1 0 0 1
0 1 0 1 0
1 1 0 1 0
0 0 1 1 0


In [18]:
def complemen(R):
    result = []
    for i in range(len(R)):
        row = []  
        for j in range(len(R)):  
            if R[i][j] == 0:
                row.append(1) 
            else:
                row.append(0)  
        result.append(row) 
    return result

In [19]:
print_matrix(complemen(R))

0 0 1 0 1
0 0 0 0 1
1 1 1 1 0
0 1 0 0 0
1 0 1 1 1
